### ISSUE TITLE
Does this work with the online microbit python editor?

### ISSUE THREAD

**Issue by Stephan-e** [Krakenus/microbit-cutebot-micropython#1]
Hi does this work with https://python.microbit.org/v/2.0 ? 

I have tried it but it keeps giving me either an OSError or i2c buffer write error. 

I will try see if I can make it work with the online complier

**Comment by Krakenus** [comment]
Hello,

I never tried the online editor personally but I believe it should work if you add the cutebot.py to Project Files (under the Save/Load button). You can also simply copy & paste the content of cutebot.py above your own code. This should always work.

I realise the way of usage I described in README is not very suitable for beginners so I will test more possibilities how to use the library and I will update the README file soon.

However in your case I think the library is imported well because you didn't get an ImportError. 
The I2C error can be raised when there is no i2c slave with expected address found. Did you plugged the microbit to you cutebot correctly? Is it powered well?
Not sure about the OSError right now. Can you post some  of your code here, please?

**Comment by Krakenus** [comment]
@Stephan-e 
Hello, 

did you make any progress? 

I just tested several methods how to work with the library (including the online editor) and described them in the README file.

**Comment by Krakenus** [comment]
More than a month without response.
I updated README and tested all of described methods so I close the issue.
